apiVersion: apps/v1
kind: Deployment
metadata:
  name: biddingexamination
  namespace: bidding
  labels:
    app: biddingexamination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biddingexamination
  template:
    metadata:
      labels:
        app: biddingexamination
    spec:
      containers:
        - name: biddingexamination
          image: user01skccacr.azurecr.io/biddingexamination:latest
          ports:
            - containerPort: 8080
          env:
            - name: bidding-url
              valueFrom:
                configMapKeyRef:
                  name: bidding-cm
                  key: url
          #readinessProbe:
          #  httpGet:
          #    path: '/actuator/health'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
          #livenessProbe:
          #  httpGet:
          #    path: '/actuator/health'
          #    port: 8080
          #  initialDelaySeconds: 120
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 5
